saisie/urls.py
from django.contrib import admin
from django.urls import path
from . import views
from ressources import views as ressources_views

#Name space


urlpatterns = [
    path('', views.index, name = 'index_saisie'),
    path('logout', views.logoutUser, name = 'logout'),
    path('pending/', views.pending, name = 'pending'),
    path('posted/', views.posted, name = 'posted'),
    path('approved/', views.approved, name = 'approved'),


    path('post_timetable/<str:pk>', views.post_timetable, name = 'post_timetable'),
    path('desactivate_timetable/<str:pk>', views.desactivate_timetable, name = 'desactivate_timetable'),
    path('send_mail/', views.send_mail, name = 'send_mail'),

    path('create_timetable/', views.generer_edt, name = 'create_timetable'),
    path('configure/', views.configure, name = 'configure'),

    #Entêtes
    path('headers/', views.headers, name = 'headers'),                                          
    path('create_header/', views.create_header, name = 'create_header'),
    path('available_ressources/', views.available_ressources, name = 'available_ressources'),                       #Creer un nouvel entete
    path('choose_header/<str:pk>', views.choose_header, name = 'choose_header'),


    path('view_timetable/<str:pk>', views.print_timetable, name = 'print_timetable'),           #afficher l'edt
    path('submit_timetable/<str:pk>', views.submit_timetable, name = 'submit_timetable'),       #Soumettre l'edt
    path('update_timetable/<str:pk>', views.update_timetable, name = 'update_timetable'),       #Modifier l'edt
    path('delete_timetable/<str:pk>', views.delete_timetable, name = 'delete_timetable'),       #Supprimer l'edt


    #Gestion des groupes d'étudiants
    path('create_group/', views.create_group, name = 'create_group'),
    path('update_group/<str:pk>', views.update_group, name = 'update_group'),
    path('delete_group/<str:pk>', views.delete_group, name = 'delete_group'),
    path('groups/', views.groups, name = 'groups'),


    #CRUD pour les ressources
    #path('create_instructor/', views.create_instructor, name = 'create_instructor'),
    path('update_instructor/<str:pk>', ressources_views.update_instructor, name = 'update_instructor'),
    #path('delete_instructor/<str:pk>', views.delete_instructor, name = 'delete_instructor'),

    #path('create_course/', views.create_course, name = 'create_course'),
    path('update_course/<str:pk>', ressources_views.update_course, name = 'update_course'),
    #path('delete_course/<str:pk>', views.delete_course, name = 'delete_course'),

   #path('create_meetingTime/', views.create_meetingTime, name = 'create_meetingTime'),
    path('update_meetingTime/<str:pk>', ressources_views.update_meetingTime, name = 'update_meetingTime'),
    #path('delete_meetingTime/<str:pk>', views.delete_meetingTime, name = 'delete_meetingTime'),

    #path('create_room/', views.create_room, name = 'create_room'),
    path('update_room/<str:pk>', ressources_views.update_room, name = 'update_room'),
    #path('delete_room/<str:pk>', views.delete_room, name = 'delete_room'),

    #path('create_department/', views.create_department, name = 'create_department'),
    path('update_department/<str:pk>', ressources_views.update_department, name = 'update_department'),
    #path('delete_department/<str:pk>', views.delete_department, name = 'delete_department'),

    #path('create_meetingTime/', views.create_meetingTime, name = 'create_meetingTime'),
    path('update_meetingTime/<str:pk>', ressources_views.update_meetingTime, name = 'update_meetingTime'),
    #path('delete_meetingTime/<str:pk>', views.delete_meetingTime, name = 'delete_meetingTime'),

    ]
    

saisie/models.py
from django.db import models
from django.utils import timezone

# Create your models here.
from ressources.models import *


TAILLE_POPULATION = 9
NOMBRE_EDT_ELUS = 1
TAILLE_SELECTION_TOURNOI = 3
TAUX_MUTATION = 0.05




class Group(models.Model):

    ACTIVITIES = (
			('Cours Magistral', 'Cours Magistral'),
			('Travaux Dirigés', 'Travaux Dirigés'),
            ('Travaux Pratiques', 'Travaux Pratiques'),
            ('Contrôle Continu', 'Contrôle Continu'),
            ('Examens', 'Examens'),
            ('Soutenances', 'Soutenances'),
            ('Autre', 'Autre')

		)


    activity = models.CharField(max_length=200, blank=True, null=True, choices=ACTIVITIES, default='Cours Magistral', verbose_name='Activité')
    department = models.ForeignKey(Department, on_delete = models.SET_NULL, blank=True, null=True, verbose_name='Classe')
    name = models.CharField(max_length=200, blank=True, null=True, verbose_name='Nom du groupe')    
    size = models.FloatField(null=True, blank=True, verbose_name='Effectif') #effectif

    def __str__(self):
        return self.name




class Level(models.Model):

    LEVEL = (
			('Niveau 1', 'Niveau 1'),
			('Niveau 2', 'Niveau 2'),
            ('Niveau 3', 'Niveau 3'),
            ('Niveau 4', 'Niveau 4'),
            ('Niveau 5', 'Niveau 5'),

		)


    level = models.CharField(max_length=200, null=True, choices=LEVEL, default='Niveau 1')

    def __str__(self):
        return self.level


class Header(models.Model):
    
    ACTIVITIES = (
			('Cours Magistral', 'Cours Magistral'),
			('Travaux Dirigés', 'Travaux Dirigés'),
            ('Travaux Pratiques', 'Travaux Pratiques'),
            ('Contrôle Continu', 'Contrôle Continu'),
            ('Examens', 'Examens'),
            ('Soutenances', 'Soutenances'),
            ('Autre', 'Autre')

		)

    SEMESTERS = (
			('Semestre 1', 'Semestre 1'),
			('Semestre 2', 'Semestre 2'),

		)
    
    semester = models.CharField(max_length=200, blank=True, null=True, choices=SEMESTERS, default='Semestre 1', verbose_name='Semestre')
    activity = models.CharField(max_length=200, blank=True, null=True, choices=ACTIVITIES, default='Cours Magistral', verbose_name='Activité')
    academic_year = models.CharField(max_length=200, blank=True, null=True, verbose_name='Année académique')
    levels = models.ManyToManyField(Level, verbose_name='Niveaux')

    def __str__(self):
        return f'{self.semester} {self.activity} {self.academic_year}'


















class Seance(models.Model):


    ACTIVITIES = (
			('Cours Magistral', 'Cours Magistral'),
			('Travaux Dirigés', 'Travaux Dirigés'),
            ('Travaux Pratiques', 'Travaux Pratiques'),
            ('Contrôle Continu', 'Contrôle Continu'),
            ('Examens', 'Examens'),
            ('Soutenances', 'Soutenances'),
            ('Autre', 'Autre')

		)

    activity = models.CharField(max_length=200, blank=True, null=True, choices=ACTIVITIES, default='Cours Magistral', verbose_name='Activité')
    dept = models.ForeignKey(Department, on_delete = models.SET_NULL, null=True, verbose_name='Classe')
    course = models.ForeignKey(Course, on_delete = models.SET_NULL, null=True, verbose_name='Course')
    instructor = models.ForeignKey(Instructor, on_delete = models.SET_NULL, null=True, verbose_name='Enseignant')
    meetingTime = models.ForeignKey(MeetingTime, on_delete = models.SET_NULL, null=True,verbose_name='Plage horaire')
    room = models.ForeignKey(Room, on_delete = models.SET_NULL, null=True, verbose_name='Salle')

    def __str__(self):
        return f'{self.course} {self.room} {self.instructor} {self.dept} {self.meetingTime}'

    


class TimeTable(models.Model):
    STATUS = (
			('actif', 'actif'),
			('Desactive', 'desactive'),
            ('soumis', 'soumis'),
            ('signe', 'signe'),
            ('en_attente', 'en_attente'),


		)

    semester = models.CharField(max_length=200, blank=True, null=True)
    classes = models.ManyToManyField(Seance)
    date_created = models.DateTimeField(default= timezone.now, null=True)
    status =  models.CharField(max_length=200, null=True, choices=STATUS, default='en_attente')
    #header = models.ForeignKey(Header, on_delete = models.SET_NULL, null=True)

    class Meta:
       ordering = ('date_created',)

saisie/templates/saisie/approved.html
{% extends 'saisie/layout/saisie_main.html' %}

{% block content %}


<!-- Begin Page Content -->
<div class="container-fluid">

	<!-- Page Heading -->
	<h1 class="h3 mb-2 text-gray-800">Emplois du temps validés   </h1>
	
	<!-- DataTales Example -->
	<div class="card shadow mb-4">
	  <div class="card-header py-3">
		<h6 class="m-0 font-weight-bold text-primary"></h6>
	  </div>
	  <div class="card-body">
		<div class="table-responsive">
		  <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
			<thead>
				<tr>
					<th>Semestre</th>
                        <th>Date de création</th>
                        			
				</tr>
			</thead>
			<tfoot>
				
			</tfoot>
			<tbody>
				{%  for timetable in approved %}
                        <tr>
                            <td> {{timetable.semester}} </td>
							<td> {{timetable.date_created}} </td>
							<td><a class="btn btn-primary" href="{% url  'print_timetable' timetable.id  %}">Voir</a></td> 
                            <td><a class="btn btn-primary" href="{% url  'post_timetable' timetable.id %}">Publier</a></td>
                            
                            
                        </tr>

                    {%  endfor %}
			</tbody>
		  </table>
		</div>
	  </div>
	</div>

  </div>

<!-- /.container-fluid -->



























{% endblock %}

saisie/templates/saisie/available_ressources.html
{% extends 'saisie/layout/saisie_main.html' %}

{% block content %}


<!-- ***************************************Bloc nouveau******************************************************* -->
<div class="row">

	<div class="col-md-6">

		<div class="card card-body">
			<a href="{% url 'create_timetable' %}" class="btn btn-primary btn-sm btn-block">Nouveau</a>
			
		</div>

	</div>
</div>


<!-- *********************************Bloc enseignants******************************************************* -->
<div class="row">

	<!-- ******************************Enseignants disponibles *******************************************-->

	
	<div class="col-md-6">
		
		<div class="card-header py-3">
			<h6 class="m-0 font-weight-bold text-primary">Enseignants disponbles  ({{total_instructors}}) </h6>
		  </div>
		<hr>
		<div class="card-body">
			
			  <table class="table table-bordered" width="50%" cellspacing="0">
				<thead>
					<tr>
						<th>Nom</th>
						<th>email</th>
						<th>Téléphone</th>
						
						<th>Modifier</th>
						
					</tr>
				</thead>
				<tfoot>
					<tr>
						<th>Nom</th>
						<th>email</th>
						<th>Téléphone</th>
						
						<th>Modifier</th>
						
					</tr>
				</tfoot>
				<tbody>
					{%  for instructor in available_instructors %}
					<tr>
						<td> {{instructor.name}} </td>
						<td> {{instructor.email}} </td>
						<td> {{instructor.phone}} </td>
						
						<td><a class="btn btn-warning" href="{% url  'update_instructor' instructor.id %}"><i class="fas fa-exclamation-triangle"></i></a></td>
						
					</tr>
	
				{%  endfor %}
				</tbody>
			  </table>
			</div>
		  </div>
		
			
			
	




	<!-- ************************** Salles disponibles *********************************************** -->
	<div class="col-md-6">
		
		<div class="card-header py-3">
			<h6 class="m-0 font-weight-bold text-primary">Salles disponbles ({{total_rooms}}) </h6>
		  </div>
		<hr>
		<div class="card-body">
			
			  <table class="table table-bordered"  width="50%" cellspacing="0">
				<thead>
					<tr>
						<th>Nom</th>
						<th>Capacité</th>
						<th>Plages horaires disponibles</th>
						<th>Modifier</th>
						
					</tr>
				</thead>
				<tfoot>
					<tr>
						<th>Nom</th>
						<th>Capacité</th>
						<th>Plages horaires disponibles</th>
						<th>Modifier</th>
						
					</tr>
				</tfoot>
				<tbody>
					{%  for room in rooms %}
						<tr>
							<td> {{room.name}} </td>
							<td> {{room.capacity}} </td>

							<td>
								<table>
									<tr>
										<th>jour</th>
										<th>Heure</th>
									</tr>

									{% for meeting_time in room.meeting_time.all %}
									{% if meeting_time.status == "Libre" %}
									<tr>
										<td>{{meeting_time.day}} </td>
										<td>{{meeting_time.time}}</td>
										
									</tr>
									{%  endif %}
									{%  endfor %}
								</table>

						    </td>

							<td><a class="btn btn-warning" href="{% url  'update_room' room.id %}"><i class="fas fa-exclamation-triangle"></i></a></td>
							
						</tr>
	
					{%  endfor %}
				</tbody>
			  </table>
			</div>
		  </div>	
</div>





	{%  endblock %}

saisie/templates/saisie/configure.html
{% extends 'saisie/layout/saisie_main.html' %}

{% block content %}


<!-- ***************************************Bloc nouveau******************************************************* -->
<div class="row">

	<div class="col-md-6">

		<div class="card card-body">
			<a href="{% url 'create_timetable' %}" class="btn btn-primary btn-sm btn-block">Nouveau</a>
			
		</div>

	</div>

	<div class="col-md-6">

		<div class="card card-body">
			<a href="{% url 'available_ressources' %}" class="btn btn-primary btn-sm btn-block">Voir les ressources disponibles</a>
			
		</div>

	</div>
</div>



	{%  endblock %}

saisie/templates/saisie/generer_edt.html
{% extends 'saisie/layout/saisie_main.html' %}

{% block content %}





<p>etat: {{timeTable.status}} </p>

<center>
<div class="row">
  <div class="col-md-6">
    <div class="card card-body">
      <form action="" method="get">

        



        <button class="btn btn-primary" type="submit">Filtrer</button>
      </form>
    </div>
  </div>

  <div class="col-md-3">
    
    
    <div class="card-body card">
      
      <a href="{% url 'send_mail' %}" class="btn btn-primary btn-sm btn-block">Notifier les enseignants par mail</a>
      
    </div>
  </div>
</div>
</center>
<hr>



<center>
  

<p>  {{timeTable.status}} </p>
<p>  {{timeTable.semester}} </p>


  
  
  <table>

    
      {% for class in timeTable.classes.all %}              
       
                    <tr>
                        <th>{{class.dept}}</th>
                        <th>{{class.course}}</th>
                        <th>{{class.room}}</th>
                        <th>{{class.instructor}}</th>
                        <th>{{class.meetingTime}}</th>
                    
                    </tr>   
                                    
              
        {% endfor %}
  </table>
  
-->
</center>


{% endblock %}

saisie/templates/saisie/group_form.html
{% extends 'saisie/layout/saisie_main.html' %}

{% block content %}


<form action="" method="POST">

    {%  csrf_token %}
     {{form}}
    <input class="btn btn-primary" type="submit" name="valider">

</form>


{% endblock %}

saisie/templates/saisie/groups.html
{% extends 'saisie/layout/saisie_main.html' %}
{%  load static %}

{% block content %}





<!-- Begin Page Content -->
<div class="container-fluid">

	<!-- Page Heading -->
	<h1 class="h3 mb-2 text-gray-800">Tous les groupes par classe</h1>
	
	<!-- DataTales Example -->
	<div class="card shadow mb-4">
	  <div class="card-header py-3">
		<h6 class="m-0 font-weight-bold text-primary"><a href="{% url 'create_group' %}">Nouveau groupe</a></h6>
	  </div>
	  <div class="card-body">
		<div class="table-responsive">
		  <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
			<thead>
				<tr>
                    <th>Classe  </th>
                    <th>Effectif Total</th>
					<th>Liste des groupes</th>
					
					
					
				</tr>
			</thead>
			<tfoot>
				
			</tfoot>

			
			<tbody>
				{%  for department in departments %}
						<tr>
							<td> {{department.name}} ({{department.group_set.all.count}}  groupes)  </td>
							<td> {{department.size}} </td>

							<td>
								<table>
									<tr>
										<th>Nom du groupe</th>
										<th>Activité</th>
										<th>Effectif</th>
										<th>Modifier</th>
										<th>Supprimer</th>

									</tr>

									{% for group in department.group_set.all %}
									
									<tr>
										<td>{{group.name}} </td>
										<td>{{group.activity}} </td>
										<td>{{group.size}} </td>
										<td><a class="btn btn-warning" href="#"><i class="fas fa-exclamation-triangle"></i></a></td>
										<td><a class="btn btn-danger" href="#"><i class="fas fa-trash"></i></a></td>
									</tr>
									
									{%  endfor %}
								</table>

						    </td>

							
							
						</tr>
	
					{%  endfor %}
			
			</tbody>
		  </table>

		  
		</div>
	  </div>
	</div>

  </div>

<!-- /.container-fluid -->





{% endblock %}

saisie/templates/saisie/header.html
{% extends 'saisie/layout/saisie_main.html' %}

{% block content %}


<form action="" method="POST">

    {%  csrf_token %}
     {{form}}
    <input class="btn btn-primary" type="submit" name="valider">

</form>





{% endblock %}

saisie/templates/saisie/header_form.html
{% extends 'saisie/layout/saisie_main.html' %}

{% block content %}


<form action="" method="POST">

    {%  csrf_token %}
     {{form}}
    <input class="btn btn-primary" type="submit" name="valider">

</form>


{% endblock %}

saisie/templates/saisie/headers.html
{% extends 'saisie/layout/saisie_main.html' %}
{%  load static %}

{% block content %}





<!-- Begin Page Content -->
<div class="container-fluid">

	<!-- Page Heading -->
	<h1 class="h3 mb-2 text-gray-800">Configuration</h1>
	
	<!-- DataTales Example -->
	<div class="card shadow mb-4">
	  <div class="card-header py-3">
		<h6 class="m-0 font-weight-bold text-primary"><a href="{% url 'create_header' %}">Ajouter une</a></h6>
	  </div>
	  <div class="card-body">
		<div class="table-responsive">
		  <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
			<thead>
				<tr>
					<th>Semestre</th>
					<th>Activité</th>
					<th>Année académique</th>
					<th>Niveaux</th>
					
					<th>choisir</th>
					<th>Modifier</th>
					<th>Supprimer</th>
				</tr>
			</thead>
			<tfoot>
				<tr>
					<th>Semestre</th>
					<th>Activité</th>
					<th>Année académique</th>
					<th>Niveaux</th>
					
					<th>choisir</th>
					<th>Modifier</th>
					<th>Supprimer</th>
				</tr>
			</tfoot>
			<tbody>
				{%  for header in headers %}
                    <tr>
                        <td> {{header.semester}} </td>
						<td> {{header.activity}} </td>
						<td> {{header.academic_year}} </td>
						<td>
							{%  for level in header.levels.all %}
							{{level}}
							<br>
							{%  endfor %}
					    </td>
						
						<td><a class="btn btn-primary" href="{% url  'choose_header' header.id %}">Choisir</a></td>
                        <td><a class="btn btn-warning" href="#"><i class="fas fa-exclamation-triangle"></i></a></td>
                        <td><a class="btn btn-danger" href="#"><i class="fas fa-trash"></i></a></td>
                    </tr>

                {%  endfor %}
			</tbody>
		  </table>
		</div>
	  </div>
	</div>

  </div>

<!-- /.container-fluid -->





{% endblock %}

saisie/templates/saisie/index_saisie.html
{% extends 'saisie/layout/saisie_main.html' %}

{% block content %}


<!-- Begin Page Content -->
<div class="container-fluid">

	<!-- Page Heading -->
	<h1 class="h3 mb-2 text-gray-800"> Tous les emplois du temps   </h1>
	
	<!-- DataTales Example -->
	<div class="card shadow mb-4">
	  <div class="card-header py-3">
		<h6 class="m-0 font-weight-bold text-primary"><a href="{% url 'configure' %}" class="btn btn-primary btn-sm btn-block">Nouvel emploi du temps</a></h6>
	  </div>
	  <div class="card-body">
		<div class="table-responsive">
		  <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
			<thead>
				<tr>
					<th>Semestre</th>
                        <th>Date de création</th>
						<th>Etat</th>
						<th>Consulter</th>				
				</tr>
			</thead>
			<tfoot>
				
			</tfoot>
			<tbody>
				{%  for timetable in timetables %}
                        <tr>
                            <td> {{timetable.semester}} </td>
                            <td> {{timetable.date_created}} </td>
							<td>{{timetable.status}}</td>
							<td><a class="btn btn-primary" href="{% url  'print_timetable' timetable.id %}"><i class="fas fa-eye"></i></a></td>
							<!-- <td><a class="btn btn-primary" href="{% url  'submit_timetable' timetable.id %}">Soumettre</a></td> -->
                            
                            
                        </tr>

                    {%  endfor %}
			</tbody>
		  </table>
		</div>
	  </div>
	</div>

  </div>

<!-- /.container-fluid -->



























{% endblock %}

saisie/templates/saisie/pending.html
{% extends 'saisie/layout/saisie_main.html' %}

{% block content %}









<!-- Begin Page Content -->
<div class="container-fluid">

	<!-- Page Heading -->
	<h1 class="h3 mb-2 text-gray-800">Emplois du temps en cours   </h1>
	
	<!-- DataTales Example -->
	<div class="card shadow mb-4">
	  <div class="card-header py-3">
		<h6 class="m-0 font-weight-bold text-primary"><a href="{% url 'headers' %}">Nouvel emploi du temps</a></h6>
	  </div>
	  <div class="card-body">
		<div class="table-responsive">
		  <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
			<thead>
				<tr>
					<th>Semestre</th>
                        <th>Date de création</th>
                        <th>Etat</th>				
				</tr>
			</thead>
			<tfoot>
				
			</tfoot>
			<tbody>
				{%  for timetable in pending %}
                        <tr>
                            <td> {{timetable.semester}} </td>
                            <td> {{timetable.date_created}} </td>
                            <td> {{timetable.status}} </td>
                            
                            <td><a class="btn btn-primary" href="{% url  'print_timetable' timetable.id %}">Voir</a></td>
                            <td><a class="btn btn-primary" href="{% url  'submit_timetable' timetable.id %}">Soumettre</a></td>
                            <td><a class="btn btn-warning"  href="{% url  'update_timetable' timetable.id %}">Modifier</a></td>
                            <td><a class="btn btn-danger" href="{% url  'delete_timetable' timetable.id %}"><i class="fas fa-trash"></i></a></td>
                        </tr>

                    {%  endfor %}
			</tbody>
		  </table>
		</div>
	  </div>
	</div>

  </div>

<!-- /.container-fluid -->



























{% endblock %}

saisie/templates/saisie/plage_horaire_form.html
{% extends 'saisie/layout/saisie_main.html' %}
{% load static %}
{% block content %}

{% endblock %}

saisie/templates/saisie/types_edt.html
<div class="row">
    <div class="col-md-2">
		
		<hr>
		<div class="card card-body">
			<a href="" class="btn btn-primary btn-sm btn-block">cours magistraux</a>
			
		</div>
    </div>

    <div class="col-md-2">
		
		<hr>
		<div class="card card-body">
			<a href="" class="btn btn-primary btn-sm btn-block">Travaux dirigés</a>
			
		</div>
    </div>

    <div class="col-md-2">
		
		<hr>
		<div class="card card-body">
			<a href="" class="btn btn-primary btn-sm btn-block">Travaux pratiques</a>
			
		</div>
    </div>

    <div class="col-md-2">
		
		<hr>
		<div class="card card-body">
			<a href="" class="btn btn-primary btn-sm btn-block">Examens</a>
			
		</div>
    </div>

    <div class="col-md-2">
		
		<hr>
		<div class="card card-body">
			<a href="" class="btn btn-primary btn-sm btn-block">Soutenances</a>
			
		</div>
    </div>

    <div class="col-md-2">
		
		<hr>
		<div class="card card-body">
			<a href="" class="btn btn-primary btn-sm btn-block">Autre</a>
			
		</div>
    </div>
</div>